### ISSUE TITLE
Issue with using certificate as env variable in freestyle pipeline from vault 

### ISSUE THREAD

**Issue by emelianrus** [jenkinsci/hashicorp-vault-plugin#119]
Hi! i'm trying load certificate from vault into pipeline and faced with issue: 

```
ERROR: Build step failed with exception
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 100.109.0.0/100.109.0.0:43828
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1057)
		at hudson.Launcher$ProcStarter.start(Launcher.java:454)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.Build$BuildExecution.build(Build.java:206)
		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
		at hudson.model.Run.execute(Run.java:1880)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:428)
java.lang.IllegalArgumentException: Invalid environment variable value: "blablabla my certificate content.... 
at java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:121)
	at java.lang.ProcessEnvironment.access$400(ProcessEnvironment.java:61)
	at java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at hudson.Proc$LocalProc.environment(Proc.java:237)
	at hudson.Proc$LocalProc.<init>(Proc.java:222)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:936)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1316)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1269)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
	at java.lang.Thread.run(Thread.java:748)
```

Jenkins - "2.235.2"
hashicorp-vault-plugin:3.6.0 (on lower versions the same error)
kubernetes:1.26.3
credentials:2.3.12

Would really appreciate any help
Thank you

**Comment by jetersen** [comment]
NOt sure with that stacktrace what vault plugin has to do with it?

See the last exception message: `Invalid environment variable value: "blablabla my certificate content.... `

**Comment by emelianrus** [comment]
i know it confusing...  
the main point that i'm using vault-plugin and the one stored certificate into vault  
* from freestyle pipeline -  i see that error 
* from "pipeline or multibranch" type and configuration like https://github.com/jenkinsci/hashicorp-vault-plugin#usage-via-jenkinsfile - all great and i can pass variable and work with it

or i missed something and this not related to vault plugin?

**Comment by emelianrus** [comment]
ok, i cant pass certificate using ENV variable 

@jetersen is it possible to pass secret from vault to pipeline using on-disk file? Like credentials secret-file binding, but without saving to credentials and adding to job settings? (that manual procedure cant be automated) 

would be very very useful when passing PKCS#12 certificates for now i cant use them...
any thoughts?

**Comment by jetersen** [comment]
Store the p12 file as base64 encoded in vault. Decode and write to file in the Jenkins pipeline?

**Comment by emelianrus** [comment]
yeap, this is how i do it now :(
that way requires to do something like this in pipeline 
```
ENVVAR=$(echo $ENVVAR | base64 -D)
```
ok, newer mind, let be base64 

Thank you for help!!!
