### ISSUE TITLE
[Question]Use of dynamic credentials causes CredentialsUnavailableException

### ISSUE THREAD

**Issue by tsologub** [jenkinsci/hashicorp-vault-plugin#164]
I was not sure whether report it as a bug or not. I decided to ask first.

I've been following your Dynamical Credentials example from the [readme part](https://github.com/jenkinsci/hashicorp-vault-plugin/blob/master/README.md#use-of-dynamic-credentials). Have some trouble in getting this example to work.

I have the following pipeline:

```groovy
import hudson.util.Secret
import com.cloudbees.plugins.credentials.CredentialsScope
import com.datapipe.jenkins.vault.credentials.VaultAppRoleCredential

vault_secrets = [
        [path: 'secrets/password-1', engineVersion: 2, secretValues: [
                [envVar: 'PASSWORD_1', vaultKey: 'PASSWORD_1']
        ]],
]

VaultAppRoleCredential appRoleCredential = new VaultAppRoleCredential(
        CredentialsScope.GLOBAL,
        'my-cred-42',
        'Some Description',
        "1234-1234-role-id",
        Secret.fromString("test-secret-id"),
        "approle"
)

pipeline {
    stages {
        stage('Prepare Vault') {
            steps {
                script {
                    vault_configuration = [vaultUrl: 'https://my-vault-url.com', vaultNamespace: 'my/namespace/here', vaultCredentialId: 'my-cred-42', engineVersion: 2]
                }
                withVault([configuration: vault_configuration, vaultSecrets: vault_secrets]) {
                    // do something
                }
            }
        }
    }
}
```

And receive the following error:
```
08:41:29  com.cloudbees.plugins.credentials.CredentialsUnavailableException: Property 'my-cred-42' is currently unavailable
08:41:29  	at com.datapipe.jenkins.vault.VaultBuildWrapper.retrieveVaultCredentials(VaultBuildWrapper.java:231)
08:41:29  	at com.datapipe.jenkins.vault.VaultBuildWrapper.provideEnvironmentVariablesFromVault(VaultBuildWrapper.java:139)
08:41:29  	at com.datapipe.jenkins.vault.VaultBuildWrapper.setUp(VaultBuildWrapper.java:94)
08:41:29  	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:146)
08:41:29  	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
08:41:29  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
08:41:29  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08:41:29  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:41:29  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:41:29  	at java.lang.Thread.run(Thread.java:748)
08:41:29  Finished: FAILURE
```

Is it really a bug, or is some configuration missing from my side?

**Comment by jetersen** [comment]
Not a bug, the credential is expected to be saved in the credential store store.

**Comment by tsologub** [comment]
That means that I need manually create `my-cred-42` in the Jenkins Credentials beforehand, and `new VaultAppRoleCredential()` from the pipeline will override them on the fly?
