### ISSUE TITLE
IllegalArgumentException with version 3.x

### ISSUE THREAD

**Issue by pappnase99** [jenkinsci/hashicorp-vault-plugin#73]
We were using v2.5.0 together with hashicorp-vault-pipeline-plugin v1.3 in a declarative pipeline and this has worked for several months. After updating to v3.1.0 (and moving back to v3.0.0) we are getting this stacktrace:

```
java.lang.IllegalArgumentException: One or more variables have some issues with their values: SECRET
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:436)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.callClosureForMapEntry(CpsDefaultGroovyMethods:5226)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.collect(CpsDefaultGroovyMethods:3446)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.collect(CpsDefaultGroovyMethods:3463)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:432)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:81)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(ModelInterpreter.groovy:484)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(ModelInterpreter.groovy:483)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:80)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:592)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.checkoutAndRun(CheckoutScript.groovy:61)
...
```

The declarative pipeline looks like this:

```
pipeline {
    agent { ... }
    environment {
        SECRET = vault path: 'path', key: 'key', credentialsId: 'credentials', engineVersion: "1"
    }
    stages { ... }
}
```

Since the hashicorp-vault-pipeline-plugin hasn't changed and has been stable for a while, i guess it's this plugin what's causing the issue. Maybe there is some parameter missing that's required now?

**Comment by casz** [comment]
@pappnase99 where was a goal to merge the two plugins but somewhat stalled.

The do not maintain the pipeline project, so I suggest you create the issue there.

**Comment by pappnase99** [comment]
I understand, however the only moving part has been this plugin. Looks like they have become incompatible. :/

**Comment by casz** [comment]
As we haven't finalized the move I suggest fixing it in the pipeline plugin first.

**Comment by corwinon** [comment]
Still relevant
